const products = [
    {
        name: "Midnight Stealth",
        img: "/products/product-1.png",
        price: 299,
        tag: "Techwear",
        url: "",
    },
    {
        name: "Arctic Frost",
        img: "/products/product-2.png",
        price: 180,
        tag: "Winter",
        url: "",
    },
    {
        name: "Desert Wanderer",
        img: "/products/product-3.png",
        price: 150,
        tag: "Adventure",
        url: "",
    },
    {
        name: "Neon Pulse",
        img: "/products/product-4.png",
        price: 220,
        tag: "Streetwear",
        url: "",
    },
    {
        name: "Urban Nomad",
        img: "/products/product-5.png",
        price: 190,
        tag: "Lifestyle",
        url: "",
    },
    {
        name: "Cobalt Strike",
        img: "/products/product-6.png",
        price: 210,
        tag: "Sport",
        url: "",
    },
    {
        name: "Forest Ranger",
        img: "/products/product-7.png",
        price: 175,
        tag: "Outdoor",
        url: "",
    },
    {
        name: "Silver Lining",
        img: "/products/product-8.png",
        price: 250,
        tag: "Premium",
        url: "",
    },
    {
        name: "Onyx Void",
        img: "/products/product-9.png",
        price: 310,
        tag: "Luxury",
        url: "",
    },
    {
        name: "Crimson Tide",
        img: "/products/product-10.png",
        price: 130,
        tag: "Casual",
        url: "",
    },
    {
        name: "Solar Flare",
        img: "/products/product-11.png",
        price: 160,
        tag: "Active",
        url: "",
    },
    {
        name: "Zenith Peak",
        img: "/products/product-12.png",
        price: 400,
        tag: "Exclusive",
        url: "",
    },
];

export default products;